### ISSUE TITLE
Bug with comments

### ISSUE THREAD

**Issue by diadorer** [chenka/html2jade.org#17]
Hi there!

Why "first_child" and "grandson" have same indents?

<img width="1280" alt="2018-10-29 20 41 15" src="https://user-images.githubusercontent.com/33423367/47669325-beb99200-dbbb-11e8-8ba2-d6f4ccda2076.png">

**Comment by diadorer** [comment]
Code with bug example:
>&lt;div&nbsp;class=&quot;parent&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&nbsp;class=&quot;first_child&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&nbsp;class=&quot;grandson&quot;&gt;grandson&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;!--&nbsp;end&nbsp;.grandson--&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;!--&nbsp;end&nbsp;.first_child--&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div&nbsp;class=&quot;second_child&quot;&gt;why???&lt;/div&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;!--&nbsp;end&nbsp;.second_child--&gt;
&lt;/div&gt;
&lt;!--&nbsp;end&nbsp;.parent--&gt;

Without **&lt;!--&nbsp;end&nbsp;.grandson--&gt;** comment all is OK.

**Comment by arinmirza** [comment]
I tried to isolate the conditions where this bug occurs.

If one or multiple `</div>` tags are between two comments, they are neglected.
```
<div class="A">
  <div class="B">
    <!-- Comment 1-->
  </div>
<!-- Comment 2 -->
<div class="C"></div>
```
As long as there are only comments, the bug occurs:
Still does not work as well
```
<div class="A">
  <div class="A">
    <div class="A">
      <!-- Comment 1 -->
      <!-- Comment 1.1 -->
      <!-- Comment 1.2 -->
    </div>
  </div>
  <!-- Comment 2-->
<div class="B">
  <div class="B">
    <div class="B">
    </div>
  </div>
</div>
```
However, adding text will make the bug disappear:
```
<div class="A">
  <div class="A">
    <div class="A">
      <!-- Comment 1 -->
      <!-- Comment 1.1 -->
      <!-- Comment 1.2 -->
      Adding this line fixes it
    </div>
    <!-- Comment 2 -->
    <!-- Comment 2.1 -->
  </div>
  <!-- Comment 3 -->
  <!-- Comment 3.1 -->
  <!-- Comment 3.2 -->
<div class="B">
  <div class="B">
    <div class="B">
    </div>
  </div>
</div>
```
