### ISSUE TITLE
Unexpected results on new site, for tag `template`

### ISSUE THREAD

**Issue by antfu** [chenka/html2jade.org#2]
Hey! I been use html2jade.org for a long time. Very happy to see it get updated! Thanks for your work! 

However, with the new site, the tag `template` seems not been converted right (it's totally ok on the former site). I haven't make a full test. Just for a quick issue.

Input: 
```html
<template>
  <div class="text-xs-center">
 
  </div>
</template>
```
Output:
```pug
template
```

**Comment by chenka** [comment]
![image](https://user-images.githubusercontent.com/837612/44140055-2e3926c6-a0a3-11e8-81d4-de6332c51326.png)

I fixed it, can you check it again?

**Comment by antfu** [comment]
Great, Thank you !
