### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by PikaBin** [chenka/html2jade.org#31]
it seems that have a problem with convert

**Comment by stayacid** [comment]
Add detais on 07/08/19:
Convertation doesn't work at all. Some errors in console:
GET https://html2jade.org/html-to-jade.js net::ERR_CONNECTION_CLOSED
GET https://html2jade.org/manifest.json net::ERR_CONNECTION_CLOSED
/favicon.ico:1 GET https://html2jade.org/favicon.ico net::ERR_CONNECTION_CLOSED
An unknown error occurred when fetching the script.

An error on converting:
Uncaught TypeError: Cannot read property 'convertHtml' of undefined

Look like some files are missing or unreachable
