### ISSUE TITLE
Case sensitive data mess up

### ISSUE THREAD

**Issue by grreeenn** [chenka/html2jade.org#4]
Hi,

Thanks for the converter - it saves plenty of precious time :)

I use it to convert Angular(2+) templates. In Angular, attribute names are case sensitive (cause they're playing much bigger roles than attribute names heh), but the converter does not process it - e.g. "*ngIf" becomes "*ngif" or "[formControl]" becomes "[formcontrol]". In these cases the resulting code won't compile, so after each conversion one need to pass through the whole file and correct these things.

Thanks for your work again :)

**Comment by grreeenn** [comment]
of course:
```
<div class="container">
      <h1 *ngIf="showHeader">Angular 2 + Google Maps Places Autocomplete</h1>
      <div class="form-group">
        <input placeholder="search for location" autocorrect="off" autocapitalize="off" spellcheck="off" type="text" class="form-control" #search [formControl]="searchControl">
      </div>
      <agm-map [latitude]="latitude" [longitude]="longitude" [scrollwheel]="false" [zoom]="zoom">
        <agm-marker [latitude]="latitude" [longitude]="longitude"></agm-marker>
      </agm-map>
    </div>
```
Look at h1's *ngIf and input's [formControl].

**Comment by antfu** [comment]
@chenka Maybe we can convert them to some format before sending them to the parser and then convert them back in pug? I am not sure if it is necessary to do that. And actually I don't understand why Angular use such "non-standard" attributes.

**Comment by antfu** [comment]
For reference, I test out some other "HTML2XXX" online converters. Seems most of them do keep the cases in there results.

http://erb2slim.com/
https://html2haml.herokuapp.com/
http://htmltohaml.com/

**Comment by grreeenn** [comment]
@chenka it would be a really nice thing to have... Impossible is sad, because on larger pieces of code such manual reconversion may be a real pain :(

@antfu Angular uses case-sensitive attribute names for bindings (so an attribute name is a function or variable name actually) and for syntactic sugar of [template structural directives](https://angular.io/guide/structural-directives).

**Comment by infrarosso78** [comment]
+1

**Comment by jchatel** [comment]
+1 I lost an hour trying to figure out why my pug integration wasn't working when in fact it was the online converter that converted incorrectly.

impossible make the converter misleading and I'm sure other people will waste time before understanding that their code was incorrectly translated.

Having some warning or text would definitely be a good way to implement "impossible"
