### ISSUE TITLE
where is settings ?

### ISSUE THREAD

**Issue by rtxrulez** [chenka/html2jade.org#6]

**Comment by snenp** [comment]
Old Version was better!

**Comment by vik407** [comment]
Sorry but the # of spaces on the config is mandatory.

**Comment by chenka** [comment]
Sorry guys, I'm working on it, will add settings in 2-3 days.

**Comment by chenka** [comment]
Added tabs and indent setting.

![image](https://user-images.githubusercontent.com/837612/44359835-2e880e00-a4e3-11e8-9710-7c329e0c6a50.png)
