### ISSUE TITLE
Tabs isn't working

### ISSUE THREAD

**Issue by alxistn** [chenka/html2jade.org#7]
It keeps spaces when I select tabs

**Comment by chenka** [comment]
I try to change between spaces and tabs and it changed to what I selected

Do you mean your code which was already pasted to editor should be changed from spaces to tabs.
Could you explain a steps to reproduce issue?

**Comment by alxistn** [comment]
I paste in code and when I select tabs it doesn't reformat the code I pasted in

**Comment by bagmetv** [comment]
Same on my side too. No action from changing numbers of spaces
