### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by nottledim** [chenka/html2jade.org#8]
I'd like a 'clear' button; to empty the source dialog - it makes cut & paste easier.

Thanks

**Comment by chenka** [comment]
what's source dialog? Did you mean HTML or Pug?

**Comment by nottledim** [comment]
Html, but i guess if one is cleared the other one must be.

**Comment by chenka** [comment]
Yeap, your are correct, just need one button.

**Comment by chenka** [comment]
Is it not convenience to press `cmd/ctrl + A` to select or text and delete.

**Comment by nottledim** [comment]
If I'm cutting and pasting with mouse then using the keyboard is not in the 
flow. Also I think that overwrites cut buffer and the html I want to paste.
